feat: apply secondary Y axis
nhn/tui.chart pull request #390
Opened 2020-09-10 08:59 UTC by jungeun-cho

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description
* feat: apply secondary y axis
<img width="997" alt="스크린샷 2020-09-10 17 57 13" src="https://user-images.githubusercontent.com/43128697/92706194-47e0a900-f38f-11ea-924e-6725849693bd.png">

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2020-09-10 10:38 UTC, jung-han commented
@jungeun-cho 

line, area, bar 차트의 경우 secondaryYAxis가 가능한데 해당 타입에 대한 secondary 생성 타입이 없는 것 같습니다.

2020-09-10 23:28 UTC, jungeun-cho commented
> line, area, bar 차트의 경우 secondaryYAxis가 가능한데 해당 타입에 대한 secondary 생성 타입이 없는 것 같습니다. 확인 부탁드립니다
line-area
line-column 등 콤보에서 사용하는 거 아닌가요?

2020-09-11 07:42 UTC, shiren requested changes
수고하셨습니다.

2020-09-11 07:42 UTC, shiren commented on src/component/axis.ts
> +    );
xAxis도 AxisType 을 이용해서 비교해주세요

2020-09-11 07:42 UTC, shiren commented on src/component/axisTitle.ts
> +    if (this.name === 'yAxis') {
가능하면 AxisType의 값은 AxisType enum을 사용해서 비교해주세요 전반적으로...

2020-09-11 07:42 UTC, shiren commented on src/store/axes.ts
> +          labelAxisOnYAxis,
이 변수명은 labelOnYAxis 가 맞는 표현 아닐까요? 전반적으로 쓰이는데 조금 햇갈려서요

2020-09-11 07:42 UTC, shiren commented on src/store/scale.ts
> +    : calculateCoordinateScale(labelOptions);
조건이 분리되어 있네요 3항으로 퉁치던지 if문으로 퉁치던지 합치면 좋을것 같아요

2020-09-14 04:30 UTC, jung-han commented on src/charts/areaChart.ts
> +    this.componentManager.add(Axis, { name: 'rightYAxis' });
`secondaryYAxis`라는 용어를 사용하고 있는데 `rightYAxis`라는 컴퍼넌트 이름으로 다르게 사용할 필요는 없을 것 같습니다.

2020-09-14 04:31 UTC, jung-han commented on src/component/axis.ts
> +  RIGHT_Y = 'rightYAxis',
SECONDARY_Y = 'secondaryYAxis' 같이 사용하면 될 것 같습니다.

2020-09-14 06:09 UTC, jung-han commented on src/helpers/axes.ts
> +export function getValidValueAxisNames(options: ChartOptionsUsingYAxis, valueAxisName: string) {
valid라는 의미가 어떤건지 알기 조금 어렵네요 ㅠㅠ 그냥 `getValueAxisNames`로 사용하면 되지 않을까요?

2020-09-14 06:29 UTC, jung-han commented on src/component/scatterSeries.ts
> +    const yAxisLimit = scale[valueAxisName].limit;
scale을 뽑아서 넘겨줘도 될 것 같습니다. 굳이 valueAxisName을 줘서 함수 내에서 꺼내지 않아도 될 것 같아요

2020-09-14 06:31 UTC, jung-han commented on src/store/axes.ts
> +  } as AxisData;
as AxisData를 제외하고 getLabelAxisData와 getValueAxisData의 반환을 `:AxisData`로 한 뒤 타입을 맞춰주는게 좋을 것 같습니다.

2020-09-14 06:35 UTC, jung-han commented on src/store/axes.ts
> +function makeDefaultYAxis(yAxis: BaseAxisOptions) {
`getDefaultYAxisState`나 `getDefaultYAxisData`같이 반환되는 단어를 적어줘야 할 것 같습니다. YAxis를 반환하는것 같아서요.

2020-09-14 06:36 UTC, jung-han commented on src/store/axes.ts
> +      yAxis: makeDefaultYAxis(yAxis),
위 함수도 비슷하게 구조를 만들어서 재사용할 수 있지않을까요?

2020-09-14 06:38 UTC, jung-han commented on src/store/layout.ts
> +function getDefaultYAxisWidth({ maxLabelWidth, size, isRightSide = false }: YAxisRectParam) {
isRightSide이미 밑에서 디스트럭처링 시 초기화를 해주고 있어서 넣어주지 않아도 될 것 같습니다.

2020-09-14 06:44 UTC, jung-han commented on src/store/scale.ts
> +  const range = dataRange;
바로 range대신 dataRange사용해도 될 것 같습니다.

2020-09-14 06:53 UTC, jung-han commented on src/component/lineSeries.ts
> +  yAxisName = 'yAxis';
제가 조금 헷갈려서 그런것 같은데..

secondaryAxis가 있을 때의 scale과 기존 yAxis의 scale이 있는것은 알겠는데,
lineSeries를 그리는데 실제 영향을 주는 scale은 두 y축 통틀어 하나여야 하지 않나요?

2020-09-14 07:03 UTC, jung-han commented on src/store/layout.ts
> +  } else if (!hasAxis || (isRightSide && !visibleRightYAxis)) {
RightSideAxis인데 visible하지 않는 경우가 있나요?

2020-09-14 07:10 UTC, jung-han commented on src/store/layout.ts
> +  if (rightYAxis?.height && plot?.height) {
Number인지를 봐야 할 것 같습니다.

2020-09-15 07:16 UTC, jungeun-cho commented on src/store/axes.ts
> +function makeDefaultYAxis(yAxis: BaseAxisOptions) {
`makeDefaultYAxisData`로 수정합니다.

2020-09-15 08:33 UTC, jungeun-cho commented on src/store/scale.ts
> +    : calculateCoordinateScale(labelOptions);
여기서 구한 result를 series.line일때 한번 더 구해주어야합니다.

2020-09-15 08:46 UTC, jungeun-cho commented on src/store/layout.ts
> +  } else if (!hasAxis || (isRightSide && !visibleRightYAxis)) {
SecondaryY축 레이아웃 계산하는데 SecondaryY축을 사용하지 않으면(옵션이 없으면) visible하지 않습니다.

2020-09-16 14:07 UTC, jungeun-cho commented on src/eventEmitter.ts
> -  | 'drawDataLabels'
사용하지 않는 이벤트 명 삭제합니다.

2020-09-16 14:09 UTC, jungeun-cho commented on src/store/seriesData.ts
> +
이 부분은 시리즈 활성화/비활성화 시 dataLabel 초기화 시켜주는 부분입니다.

2020-09-16 14:20 UTC, jungeun-cho commented on types/components/tooltip.d.ts
> +  | 'bullet';
누락된 TooltipModelName 추가합니다.

2020-09-16 14:26 UTC, jungeun-cho commented
* refactor: apply PR feedbacks
https://github.com/nhn/tui.chart/pull/390/commits/2930975592a0933463cc4d18dca96aa708377bfa
* refactor: resolve AxisData data type
https://github.com/nhn/tui.chart/pull/390/commits/06560ac509b073cd054c53267ff546ebd0ada667

2020-09-21 04:50 UTC, jung-han approved these changes
완료입니다.

2020-09-21 06:41 UTC, shiren approved these changes

2020-09-21 06:42 UTC, merged