feat : responsive layout
nhn/tui.chart pull request #413
Opened 2020-10-07 12:51 UTC by jungeun-cho

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2020-10-13 02:39 UTC, jung-han commented on src/charts/chart.ts
> +      }, 100)
디바운스 시간을 조금 늘리는건 어떤가요?_?
(매우 개인적인 의견이니 다른분들의 의견도 알려주시면 감사하겠습니다.)

2020-10-13 02:40 UTC, jung-han commented on src/store/optionsData.ts
> +import { StoreModule, Options } from '@t/store/store';
파일이름으로 그냥 `options.ts`는 어떤가요?

2020-10-13 02:40 UTC, jung-han commented on src/store/optionsData.ts
> +  name: 'optionsData',
`optionsData`대신 options를 사용하는건 어떤가요?_?

2020-10-13 05:55 UTC, lja1018 approved these changes
[10/13] 리뷰완료
고생하셨습니다!

2020-10-13 05:55 UTC, lja1018 commented on src/store/optionsData.ts
> +      state.options = options;
`state.options = getOptionsBySize({ width, height }, state.prevOptions);`는 어떤가요?

2020-10-15 05:33 UTC, jung-han commented on src/store/optionsData.ts
> +      if (!(width > 0 && height > 0)) {
`(width < 0 || height < 0)` 으로 작성하면 더 알아보기 쉬울 것 같습니다!

2020-10-15 05:46 UTC, jung-han commented on src/store/optionsData.ts
> +          return { ...acc, ...cur.options };
```js
const rules = (options.responsive as ResponsiveObjectType)?.rules;

  return Array.isArray(rules)
    ? rules.reduce((acc, cur) => {
        return cur.condition(size) ? { ...acc, ...cur.options } : acc;
      }, options)
    : options;
```

로 작성하면 타입체크가 가능할 것 같습니다.

2020-10-15 05:47 UTC, jung-han commented on src/store/optionsData.ts
> +          return { ...acc, ...cur.options };
이 부분이 `deepMergedCopy`를 사용해야 할 것 같은데 혹시 아닌가요?_?

2020-10-15 05:52 UTC, jung-han commented on src/store/optionsData.ts
> +    prevOptions: deepCopy(options),
뭔가 prevOptions보다는 사용자가 입력한 옵션이 그대로 들어오는 거니 `rawOptions`나 `originalOptions`, `userOptions`..이런 느낌은 어떠신가요?_?

2020-10-15 06:04 UTC, jung-han commented on types/options.d.ts
> +type BaseAnimation = boolean | { duration: number };
차트별로 확장되지는 않을 것 같아서 Animation으로 작성해도 좋을 것 같습니다.

```js
// store.ts
export type ChartOptions = {
  title?: string | TitleOption;
  animation?: boolean | { duration: number }; 
} & Size;
```

이 부분도 사용하고 있어서 이부분도 해당 타입으로 바꾸면 될 것 같습니다.

2020-10-15 06:08 UTC, jung-han commented on tests/store/legend.spec.ts
> -      width: 38,
추가된 액션에 관한 테스트도 필요할 것 같습니다.

2020-10-15 06:20 UTC, jung-han commented on src/component/legend.ts
> +
`this.isShow`이용하는것은 어떤가요?_?

2020-10-15 06:25 UTC, jung-han commented on src/component/exportMenu.ts
>      }
여기도 가능하다면 this.isShow이용해도 좋을 것 같습니다!

2020-10-15 06:27 UTC, jung-han commented on src/component/boxStackSeries.ts
> +      const filteredRawData = seriesRawData.filter(({ stackGroup }) => stackGroup === groupId);
`rawDataWithSameGroupId`는 너무 길까요?_?

2020-10-15 06:29 UTC, jung-han commented on src/component/circleLegend.ts
> +
이쪽도요!

2020-10-15 07:08 UTC, jung-han commented on src/charts/chart.ts
> -    const animationOption = options.chart?.animation;
firstRendering이 사라져서 옵션으로 준 duration이 계속 영향을 주고있는데 제거한 이유가 있나요?

2020-10-15 07:13 UTC, jung-han commented on src/charts/chart.ts
> +        if (this.isLooping) {
`isLooping`일 떄 리턴을 시켜줘서 인지는 모르겠지만

차트를 그릴 떄 animation duration이 길 경우 다 그려지지 않았을 떄 resizing이 일어난다면 

![image](https://user-images.githubusercontent.com/35371660/96089078-4744b080-0f01-11eb-9062-989b532af277.png)


그림처럼 차트가 그려지는 문제가 있습니다. 저번에 성호 책임님 말씀처럼 만약에 루핑중인데 리사이즈가 일어난다면 빨리 처리해버리고 하는식으로 하는건 어떤가요?_? (사실 이 문제의 해답이 될지는 해봐야 할 것 같습니다.;)

2020-10-15 07:14 UTC, jung-han requested changes
리뷰 완료입니다. 몇 가지 작성한 부분 확인 부탁드릴게요!

2020-10-15 07:30 UTC, shiren commented on src/charts/chart.ts
> +        if (this.isLooping) {
네 지금 @jung-han 의견이 제가 아까 스크럼때 이야기하려다가 만 내용입니다.
플래그보다는 기존의 animation을 재빨리 종료하는 것이 흐름 상 나아보여서요

2020-10-15 08:25 UTC, jungeun-cho commented on src/charts/chart.ts
> +            : this.getAnimationDuration(options.responsive?.animation);
`chart.animation.duration`은 초반 시리즈 렌더링에만 적용됩니다.

차트 initialize 애니메이션과 responsive 애니메이션을 다르게 주고 싶은 니즈도 있을것이라 생각했습니다.

2020-10-15 08:26 UTC, jungeun-cho commented on src/component/boxStackSeries.ts
> +      const filteredRawData = seriesRawData.filter(({ stackGroup }) => stackGroup === groupId);
명확한게 더 좋을것같아요~!

2020-10-15 08:40 UTC, jungeun-cho commented on types/options.d.ts
> +type BaseAnimation = boolean | { duration: number };
typescript/lib.dom.ts에 Animation이 정의되어 있어서요. 구분되어 사용되어야할 것같아요. 
`AnimationOptions`로 할께요.

2020-10-15 08:57 UTC, jungeun-cho commented on src/store/optionsData.ts
> +    prevOptions: deepCopy(options),
`originalOptions`옵션으로 합니다.

2020-10-16 00:21 UTC, merged