fix: resolve y axis width
nhn/tui.chart pull request #502
Opened 2021-01-13 00:33 UTC by jungeun-cho

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-01-13 08:31 UTC, lja1018 approved these changes
리뷰완료
고생하셨습니다!

2021-01-13 08:31 UTC, lja1018 commented on apps/chart/src/charts/chart.ts
> +      (!containerWidth && !containerHeight) ||
긍정형으로 `!(usingContainerWidth || usingContainerHeight) || !(containerWidth || containerHeight) ...`은 어떨까요?

2021-01-13 08:31 UTC, lja1018 commented on apps/chart/src/store/axes.ts
> +  previusAxes: Axes,
`previous` 오타네요!

2021-01-13 08:31 UTC, lja1018 commented on apps/chart/src/store/axes.ts
> +function hasYAxisTypeMaxLabelChanged(previusAxes: Axes, currentAxes: Axes): boolean {
여기도 `previous` 오타네요!

2021-01-13 08:48 UTC, jung-han commented on apps/chart/src/charts/chart.ts
> +  ro: ResizeObserver | null = null;
줄이지 않아도 될 것 같습니다 ㅎㅎ 그냥 resizeObserver 해도 될 것 같아요

2021-01-13 08:52 UTC, jung-han commented on apps/chart/src/charts/chart.ts
> +    window.removeEventListener('resize', this.debounceWindowResizeEvent);
음..의미상으로는 this.ro가 없으면 해제해줘야 하는것 맞죠?

2021-01-13 08:54 UTC, jung-han commented on apps/chart/src/charts/chart.ts
> +        }
```js
entries.forEach((entry) => {
          const { width, height } = entry.contentRect;
          this.debounceResizeEvent(width, height);
        });
```
는 어떠신가요?

2021-01-13 08:57 UTC, jung-han commented on apps/chart/src/helpers/calculator.ts
> +const ctx = document.createElement('canvas').getContext('2d')!;
이 부분 투두로 그 당시에 문제 났던 환경에서 다시 테스트 해야한다고 남겨두면 좋을 것 같습니다.
베타를 정식 나가기전에 한번 더 나가봐야겠네요

2021-01-13 09:00 UTC, jung-han approved these changes
이견없습니다. 고생하셨어요!

2021-01-13 09:14 UTC, shiren commented on apps/chart/src/charts/chart.ts
> +  ro: ResizeObserver | null = null;
+1

2021-01-13 09:14 UTC, shiren commented on apps/chart/src/charts/chart.ts
> +  ro: ResizeObserver | null = null;
네 저도 resizeObserver가 좋아 보입니다.

2021-01-13 09:16 UTC, shiren commented on apps/chart/src/charts/chart.ts
> +      this.ro!.disconnect();
좀 이상한데요? 여기서 옵셔널을 강제로 풀 필요가 있어요? if문때문에 필요 없을텐데요

2021-01-13 09:29 UTC, shiren requested changes
수고하셨습니다.

2021-01-13 09:29 UTC, shiren commented on apps/chart/src/helpers/calculator.ts
> +}
1.2는 뭐에요??

2021-01-13 09:29 UTC, shiren commented on apps/chart/src/store/axes.ts
> +  return !isUndefined(prevYAxis?.maxLabelWidth) && !isUndefined(yAxis?.maxLabelWidth)
isUndefined 로 체크하는건 언디파인드가 아닌것은 유효하다는 뜻인가요? null같은건 유효한거에요?

2021-01-13 09:29 UTC, shiren commented on apps/chart/src/store/axes.ts
> +    : false;
이 부분만 조건식이 3항식으로 하는게 오히려 특별 취급같아서 가독성이 떨어져요.
여기서 false 여야 하는 조건은 위쪽 if 조건에서 else if로 가고 마지막에 최종 리턴문만 남겨도 될것 같아요.

2021-01-14 01:37 UTC, jungeun-cho commented on apps/chart/src/helpers/calculator.ts
> +const ctx = document.createElement('canvas').getContext('2d')!;
넵!

2021-01-14 06:42 UTC, jungeun-cho commented on apps/chart/src/store/axes.ts
> +  return !isUndefined(prevYAxis?.maxLabelWidth) && !isUndefined(yAxis?.maxLabelWidth)
둘다 isNumber로 체크하도록 수정합니다.

2021-01-14 07:10 UTC, jungeun-cho commented on apps/chart/src/store/axes.ts
> +    : false;
넵. 알겠습니다 :)

2021-01-14 07:12 UTC, jungeun-cho commented on apps/chart/src/helpers/calculator.ts
> +}
css에서 `line-height: normal`일때 폰트 사이즈의 1.2배 시켜주는데요. (텍스트의 높이)
캔버스에서도 동일하게 구해주었는데 `measureText()`API의 반환값으로 계산해주도록 변경하겠습니다.

2021-01-14 07:35 UTC, jungeun-cho commented on apps/chart/src/store/axes.ts
> +    : false;
maxLabelWidth는 `isNumber`를 사용하도록 바꾸었구요~!

result값을 변수로 담기 보다는 비교조건이 충족되면 바로 반환하도록 하였습니다.

```ts
function hasYAxisMaxLabelLengthChanged(
  previousAxes: Axes,
  currentAxes: Axes,
  field: 'yAxis' | 'secondaryYAxis'
) {
  const prevYAxis = previousAxes[field];
  const yAxis = currentAxes[field];

  if (!prevYAxis?.labels && yAxis?.labels) {
    return true;
  }

  if (isNumber(prevYAxis?.maxLabelWidth) && isNumber(yAxis?.maxLabelWidth)) {
    return prevYAxis?.maxLabelWidth !== yAxis?.maxLabelWidth;
  }

  return false;
}
```

2021-01-14 08:53 UTC, merged