feat : add outlier
nhn/tui.chart pull request #557
Opened 2021-02-02 04:16 UTC by jungeun-cho

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-02-04 02:01 UTC, lja1018 approved these changes
리뷰완료
고생하셨습니다!

2021-02-04 03:27 UTC, jung-han commented on apps/chart/stories/boxPlot.stories.ts
> +export const addDataAndAddOutlier = () => {
스토리 말고 예제 페이지로 넘겨서 버튼 눌렀을때 API 호출 되게 하는건 어떠신가요?

2021-02-04 03:27 UTC, jung-han commented on apps/chart/types/index.d.ts
> +  public addOutlier(): void;
api 가이드 문서도 작성되어야 할 것 같습니다.

2021-02-04 05:13 UTC, jung-han requested changes
완료입니다~
가이드 작성 부탁드릴게요

2021-02-05 08:12 UTC, jungeun-cho commented
> 완료입니다~
> 가이드 작성 부탁드릴게요

가이드와 예제페이지 추가했습니다. 확인부탁합니다.

2021-02-09 00:16 UTC, jung-han commented on apps/chart/examples/example03-05-boxPlot-chart-add-outlier.html
> +      <a href="https://github.com/nhn/tui.chart/blob/main/docs/en/chart-boxplot.md" target="_blank">here</a>
여기 링크가 api로 가야할 것 같습니다~

2021-02-09 00:38 UTC, jung-han commented on apps/chart/examples/example03-05-boxPlot-chart-add-outlier.html
> +        chart.addOutlier(1, [[1, 10000], [3, 12000]]);
![image](https://user-images.githubusercontent.com/35371660/107299349-7ab3d800-6aba-11eb-8eed-002bf234c866.png)

현재는 하나만 추가되는 것 같아서요!
혹시 랜덤 데이터로 생성되게 하는 것은 어떠신가요? 계속 누르는 사용자가 분명 있을 것 같은데 버그로 인식할거같아요.

2021-02-09 01:45 UTC, jung-han approved these changes
예제페이지 링크만 확인 부탁드릴게요! 고생하셨습니다~

2021-02-15 00:23 UTC, jungeun-cho commented on apps/chart/examples/example03-05-boxPlot-chart-add-outlier.html
> +        chart.addOutlier(1, [[1, 10000], [3, 12000]]);
<img width="827" alt="스크린샷 2021-02-15 09 18 48" src="https://user-images.githubusercontent.com/43128697/107893596-6b77d300-6f6f-11eb-97b7-0574e7e4c94e.png">

랜덤 데이터를 사용하도록 예제를 수정합니다.

2021-02-15 00:35 UTC, merged