fix: get chart el top, left position after rendering
nhn/tui.chart pull request #578
Opened 2021-02-17 03:13 UTC by jung-han

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

#559 

## before
![image](https://user-images.githubusercontent.com/35371660/108151079-42934180-7119-11eb-8388-8b4ef46c9cca.png)

## after

![image](https://user-images.githubusercontent.com/35371660/108151180-7bcbb180-7119-11eb-83c4-a486497ac7a0.png)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-02-17 07:17 UTC, lja1018 approved these changes
리뷰완료
고생하셨습니다!

2021-02-17 07:54 UTC, jungeun-cho commented on apps/chart/src/component/exportMenu.ts
> +    });
render 함수에서 지연을 거는것은 위험해보입니다.
처음 버튼 클릭 시 너비를 캐시해두고 사용하는건어때요?

responsive 일때도 테스트 부탁드려요. 차트 크기 변경 후 정상적으로 나오는지도요~!

2021-02-17 07:54 UTC, jungeun-cho requested changes
리뷰완료했습니다~!

2021-02-18 00:33 UTC, jungeun-cho approved these changes
확인했습니다~ 수고하셨어요.

2021-02-18 00:34 UTC, merged

2021-02-18 07:32 UTC, Han-Jiho commented
이거땜에 진땀뺐는데 고쳐주셔서 감사합니다 ㅎㅅㅎ