fix: resolve init series animation on responsive
nhn/tui.chart pull request #589
Opened 2021-02-19 05:44 UTC by jungeun-cho

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-02-19 06:04 UTC, shiren requested changes
확인해주세요

2021-02-19 06:04 UTC, shiren commented on apps/chart/src/component/heatmapSeries.ts
> +
사이즈가 없음으로 해서 안보임에 대한 처리는 개별 컴포넌트가 아니라 컴포넌트 밖에서 처리해야할 것 같아요
컴포넌트를 다루는 부분에서요.

2021-02-19 06:07 UTC, shiren commented on apps/chart/src/component/component.ts
> +  }
이 메서드는 위치가 변경되거나 스토어의 정보든가 다른 방법을 사용하는게 좋을것 같아요..

2021-02-22 08:30 UTC, jungeun-cho commented
@shiren @jung-han 
이 PR은 close하고 #594 로 재요청합니다.

2021-02-22 08:30 UTC, closed without merging