fix: resolve init animation with responsive
nhn/tui.chart pull request #594
Opened 2021-02-22 08:29 UTC by jungeun-cho

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-02-23 00:30 UTC, jung-han commented on apps/chart/src/charts/chart.ts
> +    );
initStore는 사라져도 되겠네요

2021-02-23 00:40 UTC, jung-han commented on apps/chart/src/charts/chart.ts
> +      setTimeout(this.init, 0);
setTimeout이 왜 사용되는지 주석으로 남겨놓으면 좋을 것 같습니다. 0도 없어도 될 것 같아요

2021-02-23 00:40 UTC, jung-han approved these changes
완료입니다.

2021-02-23 02:30 UTC, lja1018 approved these changes
리뷰완료
고생하셨습니다!

2021-02-23 05:46 UTC, shiren requested changes
@jungeun-cho @jung-han 
화상으로 설명 드렸듯 근본적으로 이 문제가 차트의 문제인지 제약으로 가야할 문제인지를 결정해야 할 것 같아요.

2021-02-24 04:14 UTC, jungeun-cho commented
@shiren @jung-han 
#600 으로 다시 올렸습니다.

2021-02-24 04:14 UTC, closed without merging