Feat: no data
nhn/tui.chart pull request #607
Opened 2021-03-05 00:20 UTC by jung-han

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

#### Default

![image](https://user-images.githubusercontent.com/35371660/110048771-d6a90e00-7d93-11eb-851d-532c16d9770e.png)

#### lang options

```js
const options = {
  lang: {
    noData: '😭No Data!!😭',
  },
};
```

![image](https://user-images.githubusercontent.com/35371660/110048802-e58fc080-7d93-11eb-9b73-320587dfabc9.png)

#### theme

```ts
interface NoDataTheme {
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: string | number;
  color?: string;
}
```

![image](https://user-images.githubusercontent.com/35371660/110046386-42d54300-7d8f-11eb-9afd-148dd6738abd.png)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-03-05 02:57 UTC, jungeun-cho requested changes
bar, column도 line, area와 동일하게 axisLabel등 아예 안보여주는것이 어떻할까요?
데이터가 없으니 scale, dataRange도 계산되지 않아도 생각됩니다.
radar, radialBar도 마찬가지고요.
<img width="1012" alt="스크린샷 2021-03-05 11 34 51" src="https://user-images.githubusercontent.com/43128697/110060498-5beaed80-7da9-11eb-8464-dd05ec79c69f.png">
<img width="1000" alt="스크린샷 2021-03-05 11 34 31" src="https://user-images.githubusercontent.com/43128697/110060503-5db4b100-7da9-11eb-81ce-a2f18837cffe.png">
<img width="1004" alt="스크린샷 2021-03-05 11 34 18" src="https://user-images.githubusercontent.com/43128697/110060504-5e4d4780-7da9-11eb-8a87-7023b25c9d14.png">
<img width="711" alt="스크린샷 2021-03-05 11 33 40" src="https://user-images.githubusercontent.com/43128697/110060506-5ee5de00-7da9-11eb-95aa-84ff355f0c58.png">
<img width="707" alt="스크린샷 2021-03-05 11 33 26" src="https://user-images.githubusercontent.com/43128697/110060508-5f7e7480-7da9-11eb-8958-31f644921606.png">

2021-03-05 02:57 UTC, jungeun-cho commented on apps/chart/src/component/noDataText.ts
> +    const DEFAULT_NO_DATA_TEXT = 'No data to display';
저희 목욜날 회의에서 상수 무조건 상단에 정의하도록 하지 않았나요?

2021-03-05 02:57 UTC, jungeun-cho commented on docs/ko/common-noDataText.md
> +간단한 예시로 텍스트의 색상을 변경해보겠습니다..
마침표 하나 제거해주세요~

2021-03-05 06:56 UTC, lja1018 approved these changes
리뷰완료
고생하셨습니다!

2021-03-05 06:56 UTC, lja1018 commented on apps/chart/stories/noDataLayer.stories.ts
> +      noData: '데이터가 없습니다!',
그냥 의견인데 이 메시지는 영어로 쓰는게 어떤가요?

2021-03-09 01:08 UTC, shiren commented
@jungeun-cho @jung-han 
라벨이 나오는건 버그아니에요? 디스크립션의 스크린샷처럼 라벨은 없이 라인과 타이틀 정도면 차트 영역이라는 것을 표현하기에  충분한 것 같아요. 그것을 표현할 수 없는 radial 같은 경우는 어쩔 수 없이 타이틀과 메시지만 나와야 할 것 같구요.

2021-03-09 01:10 UTC, shiren approved these changes
LGTM

2021-03-10 02:06 UTC, jungeun-cho approved these changes
dataRange쪽을 수정해주었네요. 리뷰완료합니다.

히트맵쪽이요 데이터 없을 때 컬러 스펙트럼 레전드도 표시안되는게 맞지 않나요?
<img width="850" alt="스크린샷 2021-03-10 11 00 46" src="https://user-images.githubusercontent.com/43128697/110564651-8fa28a80-8190-11eb-9fa6-dae1b3115fc3.png">

2021-03-10 02:42 UTC, jung-han commented
> dataRange쪽을 수정해주었네요. 리뷰완료합니다.
> 
> 히트맵쪽이요 데이터 없을 때 컬러 스펙트럼 레전드도 표시안되는게 맞지 않나요?
> <img alt="스크린샷 2021-03-10 11 00 46" width="850" src="https://user-images.githubusercontent.com/43128697/110564651-8fa28a80-8190-11eb-9fa6-dae1b3115fc3.png">

제거했습니다~

2021-03-10 03:11 UTC, merged