feat: rangeSelection feature on LineType, Column Chart
nhn/tui.chart pull request #763
Opened 2022-11-15 00:52 UTC by jwlee1108

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description
* add `rangeSelection` custom event interface
  * ```js
    chart.on('rangeSelection', (selectedRange) => {
       console.log(selectedRange);
    });
    ```
* ![rangeselection](https://user-images.githubusercontent.com/30035674/201798832-24a9650c-2d84-405d-a3fd-da52c181e537.gif)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-11-15 04:28 UTC, dotaitch requested changes
리뷰 완료합니다.

rangeSelection를 하다가 마우스가 차트를 벗어나면 rangeSelection이 도중에 멈추네요. 차트를 벗어나도 rangeSelection이 계속 되어야 하지 않을까요?
![bug_dragend](https://user-images.githubusercontent.com/8615506/201826341-baa260a3-9336-4d07-bacc-fcf342699f75.gif)

2022-11-15 04:28 UTC, dotaitch commented on apps/chart/src/charts/columnChart.ts
> + *       @param {boolean} [props.options.series.selectable=false]
설명이 사라졌네요

2022-11-15 04:28 UTC, dotaitch commented on apps/chart/src/charts/columnLineChart.ts
>  import * as basicBrush from '@src/brushes/basic';
여기는 `rangeSelectable` 설명이 없어도 되나요??

2022-11-15 04:28 UTC, dotaitch commented on apps/chart/src/charts/lineScatterChart.ts
여기도 `rangeSelectable` 설명이 없네요

2022-11-15 04:43 UTC, jwlee1108 commented on apps/chart/src/charts/lineScatterChart.ts
이건 Zoom 기능 지원이 제대로 안되는 차트인데 들어가 있었네요. 이번 PR에선 빼고 zoom 처리를 다시 확인해봐야겠어요.

2022-11-15 06:24 UTC, adhrinae approved these changes
차트 리뷰는 거의 처음 하네요. 제가 볼 수 있는 한에서는 LGTM입니다.

2022-11-15 06:24 UTC, adhrinae commented on apps/chart/src/component/rangeSelection.ts
> +        this.eventBus.emit('zoom', makeObservableObjectToNormal(dragRange));
(여담) `makeObservableObjectToNormal` 이라는 친구는 보통 다른 라이브러리에서 보면 `toJS` 와 같은 용도였군요. 함수 이름이 길길래 눈에 띄었습니다.

https://mobx.js.org/api.html#tojs

2022-11-15 06:24 UTC, adhrinae commented on apps/chart/src/store/legend.ts
> +type LegendInfoToSetIndexParams = {
이 타입은 한 번만 사용되니까 굳이 지금 분리하진 않아도 되어보이는군요.

2022-11-15 06:54 UTC, jwlee1108 commented on apps/chart/src/store/legend.ts
> +type LegendInfoToSetIndexParams = {
엇 이건 잘못 빨려들어갔네요 ㅠ 이전 상태로 복원 시키겠습니다.

2022-11-15 08:43 UTC, jwlee1108 commented
@dotaitch 

우선 기존 차트의 구조나 동작 자체가 각 컴포넌트에 `responder`라는 사용자 마우스 이벤트 수신기를 달아서 처리합니다.
zoom이나 rangeSelection은 series에 연결된 responder를 사용해야 하고 마우스가 series 영역을 넘어가는 선이 되었을 땐 이벤트를 취소 시키는게 맞긴 합니다.

만약 이 영역을 벗어날 경우 다른 컴포넌트의 responder과 동작이 겹쳐 의도치 않은 문제가 발생할 수도 있어요.
마우스가 plot을 벗어나면 드래그 처리가 취소되는 건 기존에 zoom에서도 마찬가지인데 rangeSelection은 동작 특성상 불편함이 더 두드러지네요. 

지금 생각나는대로면..`responder`가 확인하는 영역을 조금 넓힐 수는 있을 것 같은데 앞서 말씀드린 다른 컴포넌트들과의 충돌 가능성과 계산 로직 수정 범위를 보고 일정 내 처리 가능한지 확인 후 진행해보겠습니다.

2022-11-16 00:49 UTC, jajugoguma approved these changes
리뷰 완료합니다! 차트는 처음은데 꽤 어렵네요.. ㅎㅎㅎ

2022-11-16 01:51 UTC, jwlee1108 commented
@dotaitch 

`responder` 처리 영역을 차트 전역으로 바꾸면 실제로 `plot` 영역을 넘어가도 동작을 하기에 계산 로직도 조금 수정해봤는데 
`legend`나 다른 컴포넌트의 `responder`가 반응하는 문제가 발생하네요. 영역 넘어가는 건 known issue로 봐야겠습니다.

2022-11-16 02:32 UTC, dotaitch approved these changes

2022-11-16 02:33 UTC, merged